CC = gcc
CFLAGS = -Wall -Wextra -pthread
TARGETS = server client try/timestamp

all: $(TARGETS)

server: server.c
	$(CC) $(CFLAGS) -o server server.c

client: client.c
	$(CC) $(CFLAGS) -o client client.c

clean:
	rm -f $(TARGETS)
